version: '3.8'

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5

  minio:
    image: quay.io/minio/minio:latest
    ports:
      - "9000:9000"  # S3 API
      - "9001:9001"  # MinIO Console
    volumes:
      - minio_data:/data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 3s
      retries: 5

  # Uncomment if you want to run the collaborative editor backend in Docker
  # collaborative-server:
  #   build: ./backend
  #   ports:
  #     - "3001:3001"
  #   environment:
  #     - REDIS_URL=redis://redis:6379
  #     - PORT=3001
  #     - HOST=0.0.0.0
  #   depends_on:
  #     redis:
  #       condition: service_healthy
  #   restart: unless-stopped

  # Uncomment if you want to run the worker in Docker
  # collaborative-worker:
  #   build: ./backend
  #   command: node worker.js
  #   environment:
  #     - REDIS_URL=redis://redis:6379
  #   depends_on:
  #     redis:
  #       condition: service_healthy
  #   restart: unless-stopped

volumes:
  redis_data:
    driver: local
  minio_data:
    driver: local

networks:
  default:
    name: collaborative-editor
    driver: bridge 